[project]
name = "netxms-doc"
version = "1.1.0"
description = "NetXMS Documentation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sphinx==8.2.3",
    "sphinx-autobuild==2025.8.25",
    "sphinx-intl==2.3.2",
    "sphinx-rtd-theme==3.1.0",
]
